import type { EntityCollection } from "./entity-views"
export const entityNames: Record<EntityCollection, string> = {
  customers: "Клиент",
  bookings: "Бронирование",
  team: "Сотрудник",
  routes: "Маршрут",
  fleet: "Автомобиль",
  requests: "Индивидуальная заявка",
  availability: "Блокировка дат",
  trips: "Рейс",
  "cash-balances": "Касса водителей",
}
export function entityDetailHref(entity: EntityCollection, id: string) {
  return `/${entity}/${encodeURIComponent(id)}`
}
export const entityFieldLabels: Record<string, string> = {
  first_name: "Имя",
  last_name: "Фамилия",
  phone: "Телефон",
  passengers: "Пассажиры",
  latitude: "Широта",
  longitude: "Долгота",
  accuracy_meters: "Точность, м",
  recorded_at: "Получено",
  driver_id: "ID водителя",
  id: "ID",
  full_name: "Имя и фамилия",
  display_name: "Имя",
  name: "Название",
  phone_e164: "Телефон",
  passenger_phone_e164: "Телефон пассажира",
  customer_phone: "Телефон клиента",
  email: "Email",
  telegram_id: "Telegram ID",
  origin_name: "Откуда",
  destination_name: "Куда",
  starts_at: "Отправление",
  ends_at: "Прибытие / окончание",
  requested_departure_at: "Желаемое отправление",
  created_at: "Создано",
  updated_at: "Обновлено",
  imported_at: "Импортировано",
  processed_at: "Обработано",
  payment_hold_expires_at: "Бронь удерживается до",
  currency: "Валюта",
  seats: "Пассажиров",
  capacity: "Вместимость",
  price_minor: "Стоимость",
  default_price_minor: "Базовая цена",
  pricing_mode: "Модель цены",
  default_pricing_mode: "Модель цены",
  is_active: "Статус",
  is_system: "Системный пользователь",
  role: "Роль",
  status: "Статус",
  kind: "Тип рейса",
  source: "Источник",
  notes: "Заметки",
  reason: "Причина",
  comment: "Комментарий клиента",
  operator_note: "Комментарий диспетчера",
  passenger_name: "Пассажир",
  passenger_birth_date: "Дата рождения",
  registration_number: "Госномер",
  vehicle_class: "Класс транспорта",
  vehicle_name: "Автомобиль",
  driver_name: "Водитель",
  driver_phone: "Телефон водителя",
  route_name: "Маршрут",
  customer_name: "Клиент",
  payment_status: "Статус оплаты",
  payment_method: "Метод оплаты",
  birth_date: "Дата рождения",
  user_id: "ID пользователя",
}
export const relationFields: Record<string, EntityCollection> = {
  customer_id: "customers",
  trip_id: "trips",
  route_id: "routes",
  vehicle_id: "fleet",
}
export const valueLabels: Record<string, string> = {
  developer: "Разработчик",
  owner: "Владелец",
  admin: "Администратор",
  dispatcher: "Диспетчер",
  driver: "Водитель",
  draft: "Черновик",
  new: "Новый",
  assigned: "Назначен",
  active: "Активный",
  inactive: "Неактивный",
  temporarily_unavailable: "Временно недоступный",
  archived: "Архив",
  in_progress: "В пути / в работе",
  completed: "Завершён",
  cancelled: "Отменён",
  closed: "Закрыт",
  pending: "Ожидание",
  awaiting_payment: "Ожидает оплаты",
  cash_on_boarding: "Наличными при посадке",
  confirmed: "Подтверждён",
  expired: "Истёк",
  paid: "Оплачен",
  cash: "Наличные",
  bank_transfer: "Банковский перевод",
  regular: "Регулярный",
  individual: "Индивидуальный",
  per_passenger: "За пассажира",
  per_booking: "За бронь",
  telegram: "Telegram",
  dispatcher_source: "Диспетчер",
  web: "Сайт",
  import: "Импорт",
}
